version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: .
    container_name: backend
    ports:
      - "9000:9000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
